pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl"
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl"



threshold:
  swipe: 0.5
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.3
